name: libphonenumber_plugin
description: Flutter package for Google libphonenumber.
version: 0.1.0
homepage: https://github.com/natintosh/plugin_libphonenumber.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  
  libphonenumber_platform_interface: ^0.2.0

  libphonenumber_web: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/libphonenumber_plugin/js/libphonenumber.js
    - packages/libphonenumber_plugin/js/stringbuffer.js
    - assets/js/libphonenumber.js
    - assets/js/stringbuffer.js

  plugin:
    platforms:
      web:
        default_package: libphonenumber_web
